jobs:
  build:
    name: Test with ${{ matrix.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      id: sdkman
      name: Download ${{ matrix.version }}
      uses: sdkman/sdkman-action@master
      with:
        candidate: java
        version: ${{ matrix.version }}
    - continue-on-error: true
      name: Set up ${{ matrix.version }}
      uses: actions/setup-java@v1
      with:
        java-version: 8
        jdkFile: ${{ steps.sdkman.outputs.file }}
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -V verify
    strategy:
      matrix:
        version:
        - 8.0.275.hs-adpt
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___build.yml
