jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build docs
      run: ./mvnw clean package -Pdocs,spring -DskipTests=true
    - continue-on-error: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_KEY }}
      name: Upload to S3
      run: 'aws s3 sync --delete --acl public-read docs/target/generated-docs/ s3://awspring-docs/spring-cloud-aws/docs/

        aws cloudfront create-invalidation --distribution-id EA7LER7CI960A --paths
        "/*"

        '
name: Build and upload docs
on:
  repository_dispatch:
    types: trigger-ga___upload-docs.yml
